### ISSUE TITLE
Module not found, no matter what.

### ISSUE THREAD

**Issue by Purpzie** [ohlookitsAugust/discordbots-api#1]
I've installed it in the exact same location as all the other modules I have (which includes discord.js which is actually running the bot), yet it still isn't able to find this one, apparently.

**Comment by ohlookitsAugust** [comment]
Hmm..

**Comment by ohlookitsAugust** [comment]
Did you do `require('discordbots-api')`?

**Comment by Purpzie** [comment]
Yep.

**Comment by ohlookitsAugust** [comment]
Ok, I may have to rewrite it.
